<a href="https://colab.research.google.com/github/Samiya-AW/Mathematics-for-Deep-Learning/blob/main/NumPy_for_Vector_%26_Matrix_Operations_in_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**What is NumPy?**

NumPy = Numerical Python

NumPy is a Python library used to work with vectors, matrices and tensors efficiently.

###**Vector**

In [ ]:
# import NumPy library

import numpy as np

In [ ]:
# Create two vectors a and b

a = np.array([1, 2, 3])
print(a)
b = np.array([3, 4, 5])
print(b)

[1 2 3]
[3 4 5]


In [ ]:
# Addition of two vectors a + b
a + b

array([4, 6, 8])

In [ ]:
# Subtraction of two vectors a - b
a - b

array([-2, -2, -2])

In [ ]:
# Increase the length of vector a by 2
# Do so by multiplying a by scalar value 2
# Scalar product of a vector

a * 2

array([2, 4, 6])

In [ ]:
# Dot product of two vectors a and b

# Basic intuition
(a[0] * b[0]) + (a[1] * b[1]) + (a[2] * b[2])

# Using NumPy
dot_product = np.dot(a, b)
print(dot_product)

26


In [ ]:
# Magnitude and unit of a vector

# Basic intuition of magnitude
m_a = ((a[0]**2) + (a[1]**2) + (a[2]**2))**0.5
print(m_a)

# Using NumPy
m = np.linalg.norm(a)
print(m)

# Unit Vector
uv_a = a / m
print(uv_a)

# Magnitude of resultant unit vector (uv_a) will be equal to 1
print(np.linalg.norm(uv_a))

3.7416573867739413
3.7416573867739413
[0.26726124 0.53452248 0.80178373]
1.0


###**Matrices**

In [ ]:
# Create two matrices named A and B

A = np.array([[1, 2], [3, 4]])
B = np. array([[1, 0], [5, 6]])
A.shape, B.shape

((2, 2), (2, 2))

In [ ]:
# Addition of two matrices A and B
A + B

array([[ 2,  2],
       [ 8, 10]])

In [ ]:
# Subtraction of two matrices A and B
A - B

array([[ 0,  2],
       [-2, -2]])

In [ ]:
# Multiplication of two matrices A and B
print(A.shape, B.shape)
A @ B

# OR

np.dot(A, B)

(2, 2) (2, 2)


array([[11, 12],
       [23, 24]])

In [ ]:
# Scalar multiplication of matrix A
3 * A

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
# Determinant of matrix A

# Basic intuition
det = ((A[0][0] * A[1][1]) - (A[0][1] * A[1][0]))
print(det)

# Using NumPy
det_A = np.linalg.det(A)
print(det_A)

-2
-2.0000000000000004
